### ISSUE TITLE
No PHP file in downloads

### ISSUE THREAD

**Issue by organicstacks** [dgraves/embeddedalbums#1]
As you mentioned in Read me file that you have placed small PHP code but I couldn't find anywhere in download file.

**Comment by dgraves** [comment]
The PHP code is in a file named picasaweb.inc.  I have updated the README to clarify.  The picasaweb.inc file was intended to be used with Drupal as something like:
<?php
    include('files/embeddedalbums/picasaweb.inc');
    picasa_create_album('myuserid', 'MyAlbumName');
?>
